// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvIqYFijd29rEhsmU86n1tj_IHa0PGWFc',
    appId: '1:433770674222:web:16c6479d439eda377c47bf',
    messagingSenderId: '433770674222',
    projectId: 'diabetes-app-d7718',
    authDomain: 'diabetes-app-d7718.firebaseapp.com',
    storageBucket: 'diabetes-app-d7718.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUKP_gtuSOnYHlUHrZgfUY0ebVgOnlXbg',
    appId: '1:433770674222:android:094a5ff93a941a4b7c47bf',
    messagingSenderId: '433770674222',
    projectId: 'diabetes-app-d7718',
    storageBucket: 'diabetes-app-d7718.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrCgFwWK1F8LcDlINJG3-uS4IoOosN2nY',
    appId: '1:433770674222:ios:c52c9c5234a647027c47bf',
    messagingSenderId: '433770674222',
    projectId: 'diabetes-app-d7718',
    storageBucket: 'diabetes-app-d7718.firebasestorage.app',
    iosBundleId: 'com.example.diabties',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrCgFwWK1F8LcDlINJG3-uS4IoOosN2nY',
    appId: '1:433770674222:ios:c52c9c5234a647027c47bf',
    messagingSenderId: '433770674222',
    projectId: 'diabetes-app-d7718',
    storageBucket: 'diabetes-app-d7718.firebasestorage.app',
    iosBundleId: 'com.example.diabties',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvIqYFijd29rEhsmU86n1tj_IHa0PGWFc',
    appId: '1:433770674222:web:1d19d1f3be8d65567c47bf',
    messagingSenderId: '433770674222',
    projectId: 'diabetes-app-d7718',
    authDomain: 'diabetes-app-d7718.firebaseapp.com',
    storageBucket: 'diabetes-app-d7718.firebasestorage.app',
  );

}